version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app           # Mount local backend folder into container
      - /app/node_modules        # Keep container's node_modules isolated
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app          # Mount local frontend folder into container
      - /app/node_modules        # Keep container's node_modules isolated
    restart: unless-stopped
